"""time_updated column in SessionState

Revision ID: 583bb9265086
Revises: 77821c9a0397
Create Date: 2022-09-16 20:06:11.376051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583bb9265086'
down_revision = '77821c9a0397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_states', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('session_states', 'ended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_states', sa.Column('ended', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('session_states', 'time_updated')
    # ### end Alembic commands ###
