"""rename one column in SessionStateModel, add 2 colunms in PlayersSessions

Revision ID: 77821c9a0397
Revises: 0614a347ab6c
Create Date: 2022-09-12 20:40:55.584121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77821c9a0397'
down_revision = '0614a347ab6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_players_sessions', sa.Column('can_answer', sa.Boolean(), nullable=False))
    op.add_column('association_players_sessions', sa.Column('can_choose_question', sa.Boolean(), nullable=False))
    op.add_column('session_states', sa.Column('last_answerer', sa.BigInteger(), nullable=True))
    op.drop_constraint('session_state_current_answerer_fkey', 'session_states', type_='foreignkey')
    op.create_foreign_key(None, 'session_states', 'players', ['last_answerer'], ['id'], ondelete='CASCADE')
    op.drop_column('session_states', 'current_answerer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_states', sa.Column('current_answerer', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session_states', type_='foreignkey')
    op.create_foreign_key('session_state_current_answerer_fkey', 'session_states', 'players', ['current_answerer'], ['id'], ondelete='CASCADE')
    op.drop_column('session_states', 'last_answerer')
    op.drop_column('association_players_sessions', 'can_choose_question')
    op.drop_column('association_players_sessions', 'can_answer')
    # ### end Alembic commands ###
